language: ruby
rvm:
- 2.4.2
deploy:
  api_key:
    secure: CV3GoU3Yc9uMYuUVz/DRgwkp92dy/Mn8covl6Y0epvC+pYIkr4SKUi9AnnDK27dsvnUh0WODDHya3io3USarJhhjwIEq0MKe4c8RQ6CPGEM8wdgf5tT1NYinsor0NvHaQj7pz3mHzChdakC/R3mgpblwhzVBscZQdO4FHTdOt3w4TgGdLpUaTeZtHsYQu9mdUMrGVB8x/PJEXvLcKkch3fivMaIQzv2tSHLP9xvaLBk2h3oTXRq9sufMEb25CEjI211mGY3XjEpFh1J27yZvy8abHZgYSoBBHIAW91ZT/hMx8rI55F8UUohH0XCAEWbF+JTzw6fAM4NyjNVrQEJRKF82B1GXtBSDgl7UT+zt345vgflAk36EBHfFcXpdfPvviNrzgA73IsEhT7zPKHmFykIpUbdTueTWIOqaiTom0krlcjawOS3XQSX+pkPwMECxsUVhILIC49JQl+v1jp9r1w3wgH8bD9OdiSpBM5S4ym+KyiIGQXh94tjKG6Ttg3DKeQSz/AzcxIozakVLM4uWwLCgSqFZmVhU6YA0EpNLtP6Rnf2xUDfFRKtFBNliKntC7qtnten3AyYeZCXfHXDfKX/++zB82W/rPa8B/nvXx5n5iV4sOcp5Zdt1yC+weGvkE8ySYBtynen4QUZaXjtMSZKJ7eL0Tmc4bfzrQO3UJEw=
