language: ruby
rvm:
- 2.4.2
deploy:
  provider: heroku
  api_key:
    secure: pGgg7w8stQUZv5ocqb3Zdu/KiH+wei4uz3bMQDudnBFTpbYTZOiJx7wLdzzQRwL98oDY9oajpaEp4JX8WzuyGI4snze8Ph9W8mBMu7k1MxET0UQh76ze2P4nnJg2AGKKwlmfo3AjJlaDDEiJMkvTDHu2PLITcCKPNFMN5p14W0oXkqzEM8Z4JtCMfEUYF9DrSxMMx76sss8mrpAr5lNq/rCAD5JneDhK0HEbB9yFMyCSk9X/72AIiC4aKUkzL6/S6QChAPbDRxShis/IzF02FFxyTmhQXKE4dIE+9Er+7DyYfz2YyFPx14roqdshPJBtNnPsDwVyotyfajxaozFcY/IWNeICju5gxmcPUnhE+s7TsJwkslNCqE1qounap6MB4tbTYSDNx9HfKwVzPaopHzFrPHRjOwEf2BAi+6W0LiRZLsm3TQB1J1fPgxXiJVANT88bdBsM28lf1MJX6QWwqTXwdtTuSvNN7+eok/Hv+K+5TtMuMF+7pz71bG98dA3m6C9lvFFVMUgoLukCOPCpBWY2k8dpuJBUM9oyjjWl61SAAXGtqeh7UxE+Y5qM1fuSF8RiNgeA5H0v5qh7jVnxF/ROvB2nDz0KymfxDmW3Ob0hcBEjp7Lm5FBEsNJUyXkwu4MmNn/KJzvKzKgUh0Jrw9TDWtXXuR1EFNbiEkiPDcE=
